schemaName: project_1070232728873504769

dataSources:
  ds_0:
    url: jdbc:mysql://10.129.60.118:3306/project_1070232728873504769_0?serverTimezone=UTC&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  ds_1:
    url: jdbc:mysql://10.129.60.118:3306/project_1070232728873504769_1?serverTimezone=UTC&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50

shardingRule:
  tables:
    edo:
      actualDataNodes: ds_0.edo_0, ds_1.edo_1
      tableStrategy:
        inline:
          shardingColumn: project_id
          algorithmExpression: edo_${project_id % 2}
#      keyGeneratorColumnName: order_id
#    t_order_item:
#      actualDataNodes: ds_${0..1}.t_order_item_${0..1}
#      tableStrategy:
#        inline:
#          shardingColumn: order_id
#          algorithmExpression: t_order_item_${order_id % 2}
#      keyGeneratorColumnName: order_item_id
  bindingTables:
    - edo
  defaultDatabaseStrategy:
    inline:
      shardingColumn: project_id
      algorithmExpression: ds_${project_id % 2}
  defaultTableStrategy:
    none:
  defaultKeyGeneratorClassName: io.shardingsphere.core.keygen.DefaultKeyGenerator
